### PR TITLE
Added responsive media queries

### PR DESCRIPTION
**Pull request by ktSuW**

### CODE REVIEW

**Comment by ktSuW** [comment]
I did not pull the remote main repo before I push the code. Please ignore this PR request.

**Comment by ktSuW** [comment]
1. Modified grid to flexbox - to practice flexbox
2. Added media queries for breakpoints

image
image
image
image

**Comment by ktSuW** [comment]
Hi @chelseal , I forgot to create separate branches for dark/light mode and modal popups 😅. Code (Not working) are commented in this PR.  I will create separate branches and debug them. Thanks!

**Comment by chelseal** [comment]
OK no worries 👍

**Pull request merged**
